FBAsolver: 2.0
COBRAsolver: 1.0
tend: 0.1
timeStepSize: 0.02
saveLoadedModelsToFile: 0.0
readInitialStateFrom: []
readInitialStateSelection: 2.0
readInitialStateResetTime: 0.0
parallel: 0.0
maxWorkers: 8.0
dopFBA: 1.0
doMin2PrevFlux: 1.0
fluxTolerance: 1.0E-6
minimalGrowth: 1.0E-6
solverType: 0.0
doMassBalance: 0.0
logLevel: 1.0
augmentedEuler: 1.0
myAccuracy: 1.0E-15
myBioAccuracy: 1.0E-15
SteadyStateAccuracy: 1.0E-5
maxDeviation: 5.0
biomassReductionFactor: 2.0
recordLimitingFluxes: 0.0
recording: 0.0
minRelaxValue: 1.0E-11
maxRelaxValue: 1.0
solver: 2.0
nonNegative: 0.0
relTol: 1.0E-9
absTol: 1.0E-9
agoraVersion: 1
speciesToConsider: [46.0, 125.0, 164.0, 178.0, 245.0, 270.0, 362.0, 482.0]
modelDir: ["models/AGORA-1.01-Western-Diet/"]
diet: []
