function [ returnModels, extMetab ] = prepareFBAmodel_773Agora(speciesToConsider, directory, FBAsolver)
%prepareFBAmodel Loading species given as index list in speciesToConsider
%   Detailed explanation goes here

filenames = {
'Abiotrophia_defectiva_ATCC_49176.xml' ...
'Acidaminococcus_fermentans_DSM_20731.xml' ...
'Acidaminococcus_intestini_RyC_MR95.xml' ...
'Acidaminococcus_sp_D21.xml' ...
'Acinetobacter_calcoaceticus_PHEA_2.xml' ...
'Acinetobacter_haemolyticus_NIPH_261.xml' ...
'Acinetobacter_johnsonii_SH046.xml' ...
'Acinetobacter_junii_SH205.xml' ...
'Acinetobacter_lwoffii_WJ10621.xml' ...
'Acinetobacter_pittii_ANC_4052.xml' ...
'Acinetobacter_radioresistens_NIPH_2130.xml' ...
'Actinobacillus_pleuropneumoniae_L20.xml' ...
'Actinomyces_cardiffensis_F0333.xml' ...
'Actinomyces_georgiae_DSM_6843.xml' ...
'Actinomyces_graevenitzii_C83.xml' ...
'Actinomyces_naeslundii_str_Howell_279.xml' ...
'Actinomyces_odontolyticus_ATCC_17982.xml' ...
'Actinomyces_oris_K20.xml' ...
'Actinomyces_turicensis_ACS_279_V_Col4.xml' ...
'Actinomyces_urogenitalis_DSM_15434.xml' ...
'Actinomyces_viscosus_C505.xml' ...
'Adlercreutzia_equolifaciens_DSM_19450.xml' ...
'Aerococcus_viridans_ATCC_11563.xml' ...
'Aeromonas_caviae_Ae398.xml' ...
'Aeromonas_hydrophila_subsp_hydrophila_ATCC_7966.xml' ...
'Aeromonas_jandaei_Riv2.xml' ...
'Aeromonas_media_WS.xml' ...
'Aeromonas_veronii_B565.xml' ...
'Afipia_birgiae_34632.xml' ...
'Aggregatibacter_aphrophilus_NJ8700.xml' ...
'Akkermansia_muciniphila_ATCC_BAA_835.xml' ...
'Alcaligenes_faecalis_subsp_faecalis_NBRC_13111.xml' ...
'Alcaligenes_faecalis_subsp_faecalis_NCIB_8687.xml' ...
'Alistipes_finegoldii_DSM_17242.xml' ...
'Alistipes_indistinctus_YIT_12060.xml' ...
'Alistipes_onderdonkii_DSM_19147.xml' ...
'Alistipes_putredinis_DSM_17216.xml' ...
'Alistipes_shahii_WAL_8301.xml' ...
'Alloprevotella_tannerae_ATCC_51259.xml' ...
'Anaerobaculum_hydrogeniformans_OS1_ATCC_BAA_1850.xml' ...
'Anaerobiospirillum_succiniciproducens_DSM_640001.xml' ...
'Anaerococcus_hydrogenalis_DSM_7454.xml' ...
'Anaerococcus_prevotii_DSM_20548.xml' ...
'Anaerococcus_vaginalis_ATCC_51170.xml' ...
'Anaerofustis_stercorihominis_DSM_17244.xml' ...
'Anaerostipes_caccae_DSM_14662.xml' ...
'Anaerostipes_hadrus_DSM_3319.xml' ...
'Anaerostipes_sp_3_2_56FAA.xml' ...
'Anaerotruncus_colihominis_DSM_17241.xml' ...
'Aneurinibacillus_aneurinilyticus_ATCC_12856.xml' ...
'Arcanobacterium_haemolyticum_DSM_20595.xml' ...
'Arcobacter_butzleri_RM4018.xml' ...
'Arthrobacter_castelli_DSM_16402.xml' ...
'Atopobium_minutum_10063974.xml' ...
'Atopobium_parvulum_DSM_20469.xml' ...
'Atopobium_rimae_ATCC_49626.xml' ...
'Bacillus_altitudinis_41KF2b.xml' ...
'Bacillus_atrophaeus_ATCC_49822_1.xml' ...
'Bacillus_cereus_AH187_F4810_72.xml' ...
'Bacillus_cereus_G9842.xml' ...
'Bacillus_clausii_KSM_K16.xml' ...
'Bacillus_endophyticus_2102.xml' ...
'Bacillus_firmus_DS1.xml' ...
'Bacillus_flexus_27Col1_1E.xml' ...
'Bacillus_fordii_DSM_16014.xml' ...
'Bacillus_halodurans_C_125.xml' ...
'Bacillus_infantis_NRRL_B_14911.xml' ...
'Bacillus_mojavensis_RO_H_1.xml' ...
'Bacillus_mycoides_DSM_2048.xml' ...
'Bacillus_nealsonii_AAU1.xml' ...
'Bacillus_pseudofirmus_OF4.xml' ...
'Bacillus_pumilus_ATCC_7061.xml' ...
'Bacillus_sonorensis_L12.xml' ...
'Bacillus_thermoamylovorans.xml' ...
'Bacillus_timonensis_JC401.xml' ...
'Bacillus_vallismortis_DV1_F_3.xml' ...
'Bacteroides_caccae_ATCC_43185.xml' ...
'Bacteroides_cellulosilyticus_DSM_14838.xml' ...
'Bacteroides_clarus_YIT_12056.xml' ...
'Bacteroides_coprocola_M16_DSM_17136.xml' ...
'Bacteroides_coprophilus_DSM_18228.xml' ...
'Bacteroides_dorei_DSM_17855.xml' ...
'Bacteroides_eggerthii_1_2_48FAA.xml' ...
'Bacteroides_eggerthii_DSM_20697.xml' ...
'Bacteroides_faecis_MAJ27.xml' ...
'Bacteroides_finegoldii_DSM_17565.xml' ...
'Bacteroides_fluxus_YIT_12057.xml' ...
'Bacteroides_fragilis_3_1_12.xml' ...
'Bacteroides_fragilis_638R.xml' ...
'Bacteroides_fragilis_NCTC_9343.xml' ...
'Bacteroides_fragilis_YCH46.xml' ...
'Bacteroides_graminisolvens_DSM_19988.xml' ...
'Bacteroides_intestinalis_341_DSM_17393.xml' ...
'Bacteroides_massiliensis_B846dnLKV334.xml' ...
'Bacteroides_nordii_CL02T12C05.xml' ...
'Bacteroides_oleiciplenus_YIT_12058.xml' ...
'Bacteroides_ovatus_ATCC_8483.xml' ...
'Bacteroides_ovatus_SD_CC_2a.xml' ...
'Bacteroides_ovatus_SD_CMC_3f.xml' ...
'Bacteroides_pectinophilus_ATCC_43243.xml' ...
'Bacteroides_plebeius_M12_DSM_17135.xml' ...
'Bacteroides_pyogenes_DSM20611.xml' ...
'Bacteroides_salyersiae_WAL_10018.xml' ...
'Bacteroides_sp_1_1_14.xml' ...
'Bacteroides_sp_1_1_30.xml' ...
'Bacteroides_sp_1_1_6.xml' ...
'Bacteroides_sp_2_1_22.xml' ...
'Bacteroides_sp_2_1_33B.xml' ...
'Bacteroides_sp_2_1_7.xml' ...
'Bacteroides_sp_2_2_4.xml' ...
'Bacteroides_sp_20_3.xml' ...
'Bacteroides_sp_3_1_19.xml' ...
'Bacteroides_sp_3_1_23.xml' ...
'Bacteroides_sp_3_1_33FAA.xml' ...
'Bacteroides_sp_3_1_40A.xml' ...
'Bacteroides_sp_3_2_5.xml' ...
'Bacteroides_sp_4_1_36.xml' ...
'Bacteroides_sp_4_3_47FAA.xml' ...
'Bacteroides_sp_9_1_42FAA.xml' ...
'Bacteroides_sp_D1.xml' ...
'Bacteroides_sp_D2.xml' ...
'Bacteroides_sp_D20.xml' ...
'Bacteroides_sp_D22.xml' ...
'Bacteroides_stercoris_ATCC_43183.xml' ...
'Bacteroides_thetaiotaomicron_VPI_5482.xml' ...
'Bacteroides_timonensis_AP1.xml' ...
'Bacteroides_uniformis_ATCC_8492.xml' ...
'Bacteroides_ureolyticus_DSM_20703.xml' ...
'Bacteroides_vulgatus_ATCC_8482.xml' ...
'Bacteroides_xylanisolvens_SD_CC_1b.xml' ...
'Bacteroides_xylanisolvens_XB1A.xml' ...
'Barnesiella_intestinihominis_YIT_11860.xml' ...
'Bartonella_quintana_Toulouse.xml' ...
'Bifidobacterium_adolescentis_ATCC_15703.xml' ...
'Bifidobacterium_angulatum_DSM_20098.xml' ...
'Bifidobacterium_animalis_lactis_AD011.xml' ...
'Bifidobacterium_animalis_lactis_BB_12.xml' ...
'Bifidobacterium_animalis_lactis_Bi_07.xml' ...
'Bifidobacterium_animalis_lactis_Bl_04_ATCC_SD5219.xml' ...
'Bifidobacterium_animalis_lactis_CNCM_I_2494.xml' ...
'Bifidobacterium_animalis_lactis_DSM_10140.xml' ...
'Bifidobacterium_animalis_lactis_V9.xml' ...
'Bifidobacterium_bifidum_BGN4.xml' ...
'Bifidobacterium_bifidum_NCIMB_41171.xml' ...
'Bifidobacterium_bifidum_PRL2010.xml' ...
'Bifidobacterium_bifidum_S17.xml' ...
'Bifidobacterium_boum_DSM_20432.xml' ...
'Bifidobacterium_breve_HPH0326.xml' ...
'Bifidobacterium_breve_UCC2003_NCIMB8807.xml' ...
'Bifidobacterium_catenulatum_DSM_16992.xml' ...
'Bifidobacterium_coryneforme_DSM_20216.xml' ...
'Bifidobacterium_dentium_ATCC_27678.xml' ...
'Bifidobacterium_gallicum_DSM_20093.xml' ...
'Bifidobacterium_kashiwanohense_DSM_21854.xml' ...
'Bifidobacterium_longum_DJO10A.xml' ...
'Bifidobacterium_longum_E18.xml' ...
'Bifidobacterium_longum_infantis_157F_NC.xml' ...
'Bifidobacterium_longum_infantis_ATCC_15697.xml' ...
'Bifidobacterium_longum_longum_ATCC_55813.xml' ...
'Bifidobacterium_longum_longum_BBMN68.xml' ...
'Bifidobacterium_longum_longum_CCUG_52486.xml' ...
'Bifidobacterium_longum_longum_JCM_1217.xml' ...
'Bifidobacterium_longum_longum_JDM301.xml' ...
'Bifidobacterium_longum_NCC2705.xml' ...
'Bifidobacterium_mongoliense_DSM_21395.xml' ...
'Bifidobacterium_pseudocatenulatum_DSM_20438.xml' ...
'Bifidobacterium_pseudolongum_subsp_Pseudolongum_DSM_20099.xml' ...
'Bifidobacterium_ruminantium_DSM_6489.xml' ...
'Bifidobacterium_scardovii_JCM_12489.xml' ...
'Bifidobacterium_stercoris_ATCC_43183.xml' ...
'Bifidobacterium_thermacidophilum_subsp_thermacidophilum_DSM_15837.xml' ...
'Bifidobacterium_thermophilum_RBL67.xml' ...
'Bilophila_wadsworthia_3_1_6.xml' ...
'Blastococcus_massiliensis_AP3.xml' ...
'Blautia_hansenii_VPI_C7_24_DSM_20583.xml' ...
'Blautia_hydrogenotrophica_DSM_10507.xml' ...
'Blautia_obeum_ATCC_29174.xml' ...
'Blautia_producta_DSM_2950.xml' ...
'Blautia_wexlerae_DSM_19850.xml' ...
'Bordetella_hinzii_OH87_BAL007II.xml' ...
'Brachybacterium_paraconglomeratum_LC44.xml' ...
'Brachyspira_pilosicoli_B2904.xml' ...
'Bradyrhizobium_elkanii_USDA_76.xml' ...
'Brevibacillus_agri_5_2.xml' ...
'Brevibacillus_agri_BAB_2500.xml' ...
'Brevibacillus_borstelensis_AK1.xml' ...
'Brevibacillus_brevis_NBRC_100599.xml' ...
'Brevibacterium_casei_S18.xml' ...
'Brevibacterium_linens_BL2.xml' ...
'Brevibacterium_massiliense_5401308.xml' ...
'Brevundimonas_bacteroides_DSM_4726.xml' ...
'Brevundimonas_diminuta_470_4.xml' ...
'Brochothrix_thermosphacta_DSM_20171.xml' ...
'Bulleidia_extructa_W1219.xml' ...
'Burkholderia_cepacia_GG4.xml' ...
'Burkholderiales_bacterium_1_1_47.xml' ...
'Butyricicoccus_pullicaecorum_1_2.xml' ...
'Butyricimonas_synergistica_DSM_23225.xml' ...
'Butyricimonas_virosa_DSM_23226.xml' ...
'Butyrivibrio_crossotus_DSM_2876.xml' ...
'Butyrivibrio_fibrisolvens_16_4.xml' ...
'Campylobacter_coli_JV20.xml' ...
'Campylobacter_concisus_13826.xml' ...
'Campylobacter_curvus_525_92.xml' ...
'Campylobacter_fetus_subsp_fetus_82_40.xml' ...
'Campylobacter_gracilis_RM3268.xml' ...
'Campylobacter_hominis_ATCC_BAA_381.xml' ...
'Campylobacter_hyointestinalis_subsp_hyointestinalis_LMG_9260.xml' ...
'Campylobacter_jejuni_jejuni_81_176.xml' ...
'Campylobacter_jejuni_jejuni_ICDCCJ07004.xml' ...
'Campylobacter_jejuni_jejuni_M1.xml' ...
'Campylobacter_jejuni_jejuni_NCTC_11168.xml' ...
'Campylobacter_lari_RM2100.xml' ...
'Campylobacter_rectus_RM3267.xml' ...
'Campylobacter_showae_CSUNSWCD.xml' ...
'Campylobacter_upsaliensis_JV21.xml' ...
'Candidatus_Nitrososphaera_gargensis_Ga9_2.xml' ...
'Capnocytophaga_granulosa_ATCC_51502.xml' ...
'Capnocytophaga_ochracea_DSM_7271.xml' ...
'Capnocytophaga_sputigena_ATCC_33612.xml' ...
'Catenibacterium_mitsuokai_DSM_15897.xml' ...
'Cedecea_davisae_DSM_4568.xml' ...
'Cellulosilyticum_lentocellum_DSM_5427.xml' ...
'Cellulosimicrobium_cellulans_J36.xml' ...
'Cetobacterium_somerae_ATCC_BAA_47401.xml' ...
'Citrobacter_amalonaticus_Y19.xml' ...
'Citrobacter_freundii_ATCC_8090.xml' ...
'Citrobacter_freundii_UCI_31.xml' ...
'Citrobacter_koseri_ATCC_BAA_895.xml' ...
'Citrobacter_sp_30_2.xml' ...
'Citrobacter_youngae_ATCC_29220.xml' ...
'Cloacibacillus_evryensis_DSM_19522.xml' ...
'Clostridiales_sp_1_7_47FAA.xml' ...
'Clostridium_asparagiforme_DSM_15981.xml' ...
'Clostridium_bartlettii_DSM_16795.xml' ...
'Clostridium_beijerinckii_NCIMB_8052.xml' ...
'Clostridium_bifermentans_ATCC_19299.xml' ...
'Clostridium_bolteae_ATCC_BAA_613.xml' ...
'Clostridium_botulinum_A_str_ATCC_19397.xml' ...
'Clostridium_botulinum_A_str_ATCC_3502.xml' ...
'Clostridium_botulinum_A_str_Hall.xml' ...
'Clostridium_botulinum_Bf.xml' ...
'Clostridium_botulinum_E1_str_BoNT_E_Beluga.xml' ...
'Clostridium_botulinum_F_str_230613.xml' ...
'Clostridium_butyricum_DSM_10702.xml' ...
'Clostridium_butyricum_E4_str_BoNT_E_BL5262.xml' ...
'Clostridium_cadaveris_AGR2141.xml' ...
'Clostridium_celatum_DSM_1785.xml' ...
'Clostridium_cellobioparum_DSM_1351.xml' ...
'Clostridium_citroniae_WAL_17108.xml' ...
'Clostridium_clariflavum_DSM_19732.xml' ...
'Clostridium_clostridioforme_CM201.xml' ...
'Clostridium_difficile_CD196.xml' ...
'Clostridium_difficile_NAP07.xml' ...
'Clostridium_difficile_NAP08.xml' ...
'Clostridium_difficile_R20291.xml' ...
'Clostridium_glycolicum_ATCC_14880.xml' ...
'Clostridium_hathewayi_12489931.xml' ...
'Clostridium_hathewayi_DSM_13479.xml' ...
'Clostridium_hiranonis_TO_931_DSM_13275.xml' ...
'Clostridium_hylemonae_DSM_15053.xml' ...
'Clostridium_indolis_DSM_755.xml' ...
'Clostridium_innocuum_2959.xml' ...
'Clostridium_leptum_DSM_753.xml' ...
'Clostridium_methoxybenzovorans_SR3.xml' ...
'Clostridium_methylpentosum_R2_DSM_5476.xml' ...
'Clostridium_nexile_DSM_1787.xml' ...
'Clostridium_paraputrificum_AGR2156.xml' ...
'Clostridium_perfringens_ATCC_13124.xml' ...
'Clostridium_ramosum_VPI_0427_DSM_1402.xml' ...
'Clostridium_saccharogumia_DSM_17460.xml' ...
'Clostridium_saccharoperbutylacetonicum_N1_4_HMT.xml' ...
'Clostridium_sartagoforme_AAU1.xml' ...
'Clostridium_scindens_ATCC_35704.xml' ...
'Clostridium_sordellii_ATCC_9714.xml' ...
'Clostridium_sp_7_2_43FAA.xml' ...
'Clostridium_sp_L2_50.xml' ...
'Clostridium_sp_M62_1.xml' ...
'Clostridium_sp_SS2_1.xml' ...
'Clostridium_sp_SY8519.xml' ...
'Clostridium_spiroforme_DSM_1552.xml' ...
'Clostridium_sporogenes_ATCC_15579.xml' ...
'Clostridium_sporosphaeroides_DSM_1294.xml' ...
'Clostridium_sticklandii_DSM_519.xml' ...
'Clostridium_symbiosum_ATCC_14940.xml' ...
'Clostridium_symbiosum_WAL_14163.xml' ...
'Clostridium_symbiosum_WAL_14673.xml' ...
'Clostridium_tyrobutyricum_DSM_2637.xml' ...
'Clostridium_viride_DSM_6836.xml' ...
'Collinsella_aerofaciens_ATCC_25986.xml' ...
'Collinsella_intestinalis_DSM_13280.xml' ...
'Collinsella_stercoris_DSM_13279.xml' ...
'Collinsella_tanakaei_YIT_12063.xml' ...
'Coprobacillus_sp_29_1.xml' ...
'Coprobacillus_sp_D7.xml' ...
'Coprococcus_catus_GD_7.xml' ...
'Coprococcus_comes_ATCC_27758.xml' ...
'Coprococcus_eutactus_ATCC_27759.xml' ...
'Corynebacterium_ammoniagenes_DSM_20306.xml' ...
'Corynebacterium_amycolatum_SK46.xml' ...
'Corynebacterium_aurimucosum_ATCC_700975.xml' ...
'Corynebacterium_durum_F0235.xml' ...
'Corynebacterium_glucuronolyticum_ATCC_51867.xml' ...
'Corynebacterium_kroppenstedtii_DSM_44385.xml' ...
'Corynebacterium_propinquum_DSM_44285.xml' ...
'Corynebacterium_striatum_ATCC_6940.xml' ...
'Corynebacterium_tuberculostearicum_SK141.xml' ...
'Corynebacterium_ulcerans_809.xml' ...
'Corynebacterium_ureicelerivorans.xml' ...
'Cronobacter_sakazakii_ATCC_BAA_894.xml' ...
'Cryptobacterium_curtum_DSM_15641.xml' ...
'Curtobacterium_flaccumfaciens_UCD_AKU.xml' ...
'Delftia_acidovorans_SPH_1.xml' ...
'Dermacoccus_nishinomiyaensis.xml' ...
'Desulfovibrio_desulfuricans_subsp_desulfuricans_DSM_642.xml' ...
'Desulfovibrio_piger_ATCC_29098.xml' ...
'Desulfovibrio_sp_3_1_syn3.xml' ...
'Dialister_invisus_DSM_15470.xml' ...
'Dialister_succinatiphilus_YIT_11850.xml' ...
'Dietzia_cinnamea_P4.xml' ...
'Dorea_formicigenerans_ATCC_27755.xml' ...
'Dorea_longicatena_DSM_13814.xml' ...
'Dysgonomonas_gadei_ATCC_BAA_286.xml' ...
'Edwardsiella_tarda_ATCC_23685.xml' ...
'Edwardsiella_tarda_FL6_60.xml' ...
'Eggerthella_lenta_DSM_2243.xml' ...
'Eggerthella_sp_1_3_56FAA.xml' ...
'Eggerthella_sp_YY7918.xml' ...
'Eggerthia_catenaformis_OT_569.xml' ...
'Eikenella_corrodens_ATCC_23834.xml' ...
'Enterobacter_aerogenes_KCTC_2190.xml' ...
'Enterobacter_asburiae_LF7a.xml' ...
'Enterobacter_cancerogenus_ATCC_35316.xml' ...
'Enterobacter_cloacae_EcWSU1.xml' ...
'Enterobacter_hormaechei_YT2.xml' ...
'Enterobacter_hormaechei_YT3.xml' ...
'Enterobacteriaceae_bacterium_9_2_54FAA.xml' ...
'Enterococcus_asini_ATCC_700915.xml' ...
'Enterococcus_avium_ATCC_14025.xml' ...
'Enterococcus_caccae_ATCC_BAA_1240.xml' ...
'Enterococcus_casseliflavus_ATCC_12755.xml' ...
'Enterococcus_cecorum_DSM_20682.xml' ...
'Enterococcus_dispar_ATCC_51266.xml' ...
'Enterococcus_durans_ATCC_6056.xml' ...
'Enterococcus_faecalis_OG1RF_ATCC_47077.xml' ...
'Enterococcus_faecalis_TX0104.xml' ...
'Enterococcus_faecalis_TX1322.xml' ...
'Enterococcus_faecalis_TX2134.xml' ...
'Enterococcus_faecalis_V583.xml' ...
'Enterococcus_faecium_TX1330.xml' ...
'Enterococcus_gallinarum_EG2.xml' ...
'Enterococcus_hirae_ATCC_9790.xml' ...
'Enterococcus_phoeniculicola_ATCC_BAA_412.xml' ...
'Enterococcus_saccharolyticus_DSM8903.xml' ...
'Enterococcus_sp_7L76.xml' ...
'Erysipelotrichaceae_bacterium_5_2_54FAA.xml' ...
'Erysipelotrichaceae_bacterium_sp_3_1_53.xml' ...
'Escherichia_albertii_KF1.xml' ...
'Escherichia_albertii_TW07627.xml' ...
'Escherichia_coli_O157_H7_str_Sakai.xml' ...
'Escherichia_coli_SE11.xml' ...
'Escherichia_coli_str_K_12_substr_MG1655.xml' ...
'Escherichia_coli_UTI89_UPEC.xml' ...
'Escherichia_fergusonii_ATCC_35469.xml' ...
'Escherichia_hermannii_NBRC_105704.xml' ...
'Escherichia_sp_1_1_43.xml' ...
'Escherichia_sp_3_2_53FAA.xml' ...
'Escherichia_sp_4_1_40B.xml' ...
'Eubacterium_biforme_DSM_3989.xml' ...
'Eubacterium_brachy_ATCC_33089.xml' ...
'Eubacterium_cellulosolvens_6.xml' ...
'Eubacterium_cylindroides_T2_87.xml' ...
'Eubacterium_desmolans_ATCC_43058.xml' ...
'Eubacterium_dolichum_DSM_3991.xml' ...
'Eubacterium_eligens_ATCC_27750.xml' ...
'Eubacterium_hallii_DSM_3353.xml' ...
'Eubacterium_hallii_L2_7.xml' ...
'Eubacterium_limosum_KIST612.xml' ...
'Eubacterium_ramulus_ATCC_29099.xml' ...
'Eubacterium_rectale_ATCC_33656.xml' ...
'Eubacterium_rectale_M104_1.xml' ...
'Eubacterium_saphenum_ATCC_49989.xml' ...
'Eubacterium_siraeum_70_3.xml' ...
'Eubacterium_siraeum_DSM_15702.xml' ...
'Eubacterium_sulci_ATCC_35585.xml' ...
'Eubacterium_ventriosum_ATCC_27560.xml' ...
'Exiguobacterium_aurantiacum_DSM_6208.xml' ...
'Faecalibacterium_cf_prausnitzii_KLE1255.xml' ...
'Faecalibacterium_prausnitzii_L2_6.xml' ...
'Faecalibacterium_prausnitzii_M21_2.xml' ...
'Faecalibacterium_prausnitzii_SL3_3.xml' ...
'Filifactor_alocis_ATCC_35896.xml' ...
'Finegoldia_magna_ATCC_29328.xml' ...
'Flavonifractor_plautii_ATCC_29863.xml' ...
'Fusobacterium_gonidiaformans_3_1_5R.xml' ...
'Fusobacterium_gonidiaformans_ATCC_25563.xml' ...
'Fusobacterium_mortiferum_ATCC_9817.xml' ...
'Fusobacterium_necrophorum_D12.xml' ...
'Fusobacterium_nucleatum_subsp_animalis_3_1_33.xml' ...
'Fusobacterium_nucleatum_subsp_animalis_7_1.xml' ...
'Fusobacterium_nucleatum_subsp_animalis_D11.xml' ...
'Fusobacterium_nucleatum_subsp_vincentii_3_1_27.xml' ...
'Fusobacterium_nucleatum_subsp_vincentii_3_1_36A2.xml' ...
'Fusobacterium_nucleatum_subsp_vincentii_4_1_13.xml' ...
'Fusobacterium_periodonticum_1_1_41FAA.xml' ...
'Fusobacterium_periodonticum_2_1_31.xml' ...
'Fusobacterium_russii_ATCC_25533.xml' ...
'Fusobacterium_sp_4_8.xml' ...
'Fusobacterium_ulcerans_ATCC_49185.xml' ...
'Fusobacterium_varium_ATCC_27725.xml' ...
'Gemella_haemolysans_ATCC_10379.xml' ...
'Gemella_morbillorum_M424.xml' ...
'Gemella_sanguinis_ATCC700632.xml' ...
'Gemella_sanguinis_M325.xml' ...
'Geobacillus_vulcani_PSS1.xml' ...
'Gordonia_rubripertincta_NBRC_101908.xml' ...
'Gordonia_terrae_C_6.xml' ...
'Gordonia_terrae_NBRC_100016.xml' ...
'Gordonibacter_pamelaeae_7_10_1_bT_DSM_19378.xml' ...
'Granulicatella_adiacens_ATCC_49175.xml' ...
'Granulicatella_elegans_ATCC_700633.xml' ...
'Grimontia_hollisae_CIP_101886.xml' ...
'Haemophilus_haemolyticus_M19501.xml' ...
'Haemophilus_parainfluenzae_T3T1.xml' ...
'Haemophilus_sputorum_CCUG_13788.xml' ...
'Hafnia_alvei_ATCC_51873.xml' ...
'Hafnia_alvei_BIDMC_31.xml' ...
'Halococcus_morrhuae_DSM1307.xml' ...
'Helicobacter_bilis_ATCC_43879.xml' ...
'Helicobacter_canadensis_MIT_98_5491.xml' ...
'Helicobacter_cinaedi_CCUG_18818.xml' ...
'Helicobacter_pullorum_MIT_98_5489.xml' ...
'Helicobacter_pylori_26695.xml' ...
'Helicobacter_winghamensis_ATCC_BAA_430.xml' ...
'Holdemania_filiformis_VPI_J1_31B_1_DSM_12042.xml' ...
'Kallipyga_massiliensis_ph2.xml' ...
'Kandleria_vitulina_DSM_20405.xml' ...
'Kingella_oralis_ATCC_51147.xml' ...
'Klebsiella_pneumoniae_pneumoniae_MGH78578.xml' ...
'Klebsiella_sp_1_1_55.xml' ...
'Kluyvera_ascorbata_ATCC_33433.xml' ...
'Kocuria_palustris_PEL.xml' ...
'Kocuria_rhizophila_DC2201.xml' ...
'Kurthia_massiliensis_JC30.xml' ...
'Kytococcus_sedentarius_DSM_20547.xml' ...
'Lachnospira_multipara_ATCC_19207.xml' ...
'Lachnospiraceae_bacterium_sp_5_1_63FAA.xml' ...
'Lachnospiraceae_bacterium_sp_8_1_57FAA.xml' ...
'Lactobacillus_acidophilus_ATCC_4796.xml' ...
'Lactobacillus_acidophilus_NCFM.xml' ...
'Lactobacillus_amylolyticus_DSM_11664.xml' ...
'Lactobacillus_amylovorus_GRL_1112.xml' ...
'Lactobacillus_animalis_KCTC_3501.xml' ...
'Lactobacillus_antri_DSM_16041.xml' ...
'Lactobacillus_brevis_ATCC_367.xml' ...
'Lactobacillus_brevis_subsp_gravesensis_ATCC_27305.xml' ...
'Lactobacillus_buchneri_ATCC_11577.xml' ...
'Lactobacillus_casei_ATCC_334.xml' ...
'Lactobacillus_casei_casei_BL23.xml' ...
'Lactobacillus_coleohominis_101_4_CHN.xml' ...
'Lactobacillus_coryniformis_subsp_coryniformis_CECT_5711.xml' ...
'Lactobacillus_crispatus_125_2_CHN.xml' ...
'Lactobacillus_curvatus_CRL_705.xml' ...
'Lactobacillus_delbrueckii_subsp_bulgaricus_ATCC_11842.xml' ...
'Lactobacillus_delbrueckii_subsp_bulgaricus_ATCC_BAA_365.xml' ...
'Lactobacillus_fermentum_ATCC_14931.xml' ...
'Lactobacillus_fermentum_IFO_3956.xml' ...
'Lactobacillus_gasseri_ATCC_33323.xml' ...
'Lactobacillus_gastricus_PS3.xml' ...
'Lactobacillus_helveticus_DPC_4571.xml' ...
'Lactobacillus_helveticus_DSM_20075.xml' ...
'Lactobacillus_hilgardii_ATCC_8290.xml' ...
'Lactobacillus_iners_DSM_13335.xml' ...
'Lactobacillus_jensenii_1153.xml' ...
'Lactobacillus_johnsonii_DPC_6026.xml' ...
'Lactobacillus_johnsonii_NCC_533.xml' ...
'Lactobacillus_mucosae_LM1.xml' ...
'Lactobacillus_oris_F0423.xml' ...
'Lactobacillus_paracasei_subsp_paracasei_8700_2.xml' ...
'Lactobacillus_paracasei_subsp_paracasei_ATCC_25302.xml' ...
'Lactobacillus_pentosus_KCA1.xml' ...
'Lactobacillus_plantarum_JDM1.xml' ...
'Lactobacillus_plantarum_subsp_plantarum_ATCC_14917.xml' ...
'Lactobacillus_plantarum_WCFS1.xml' ...
'Lactobacillus_reuteri_CF48_3A_.xml' ...
'Lactobacillus_reuteri_F275_JCM_1112.xml' ...
'Lactobacillus_reuteri_MM2_3_.xml' ...
'Lactobacillus_reuteri_MM4_1A_.xml' ...
'Lactobacillus_reuteri_SD2112_ATCC_55730.xml' ...
'Lactobacillus_rhamnosus_GG_ATCC_53103.xml' ...
'Lactobacillus_rhamnosus_LMS2_1.xml' ...
'Lactobacillus_ruminis_ATCC_25644.xml' ...
'Lactobacillus_sakei_subsp_sakei_23K.xml' ...
'Lactobacillus_salivarius_HO66_ATCC_11741.xml' ...
'Lactobacillus_salivarius_salivarius_UCC118.xml' ...
'Lactobacillus_ultunensis_DSM_16047.xml' ...
'Lactobacillus_vaginalis_ATCC_49540.xml' ...
'Lactococcus_garvieae_ATCC_49156.xml' ...
'Lactococcus_raffinolactis_4877.xml' ...
'Laribacter_hongkongensis_HLHK9.xml' ...
'Lautropia_mirabilis_ATCC_51599.xml' ...
'Leminorella_grimontii_ATCC_33999.xml' ...
'Leptotrichia_buccalis_C_1013_b.xml' ...
'Leuconostoc_argentinum_KCTC_3773.xml' ...
'Leuconostoc_gelidum_JB7.xml' ...
'Leuconostoc_mesenteroides_subsp_cremoris_ATCC_19254.xml' ...
'Listeria_grayi_DSM_20601.xml' ...
'Listeria_monocytogenes_4a_L99.xml' ...
'Listeria_monocytogenes_4b_F2365.xml' ...
'Listeria_monocytogenes_Finland_1988.xml' ...
'Listeria_monocytogenes_FSL_R2_561.xml' ...
'Listeria_monocytogenes_J0161_FSL_R2_499.xml' ...
'Listeria_monocytogenes_serotype_7_SLCC_2482.xml' ...
'Listeria_monocytogenes_SLCC_2378.xml' ...
'Listeria_monocytogenes_SLCC_2540.xml' ...
'Listeria_monocytogenes_SLCC_7179.xml' ...
'Lysinibacillus_fusiformis_ZB2.xml' ...
'Lysinibacillus_sphaericus_C3_41.xml' ...
'Marvinbryantia_formatexigens_I_52_DSM_14469.xml' ...
'Megamonas_funiformis_YIT_11815.xml' ...
'Megamonas_hypermegale_ART12_1.xml' ...
'Megasphaera_elsdenii_DSM_20460.xml' ...
'Melainabacterium_MEL_A1.xml' ...
'Methanobrevibacter_ruminantium_M1.xml' ...
'Methanobrevibacter_smithii_ATCC_35061.xml' ...
'Methanomassiliicoccus_luminyensis_B10.xml' ...
'Methanosphaera_stadtmanae_DSM_3091.xml' ...
'Methylobacterium_mesophilicum_SR1_6_6.xml' ...
'Methylobacterium_populi_BJ001.xml' ...
'Methylobacterium_radiotolerans_JCM_2831.xml' ...
'Methyloversatilis_universalis_FAM5.xml' ...
'Methyloversatilis_universalis_Fam50001.xml' ...
'Microbacterium_gubbeenense_DSM_15944.xml' ...
'Microbacterium_oleivorans_NBRC_103075.xml' ...
'Microbacterium_paraoxydans_77MFTsu3_2.xml' ...
'Micrococcus_luteus_NCTC_2665.xml' ...
'Micromonospora_aurantiaca_ATCC_27029.xml' ...
'Mitsuokella_jalaludinii_DSM_13811.xml' ...
'Mitsuokella_multacida_DSM_20544.xml' ...
'Mobiluncus_curtisii_ATCC_43063.xml' ...
'Moraxella_catarrhalis_RH4.xml' ...
'Morganella_morganii_subsp_morganii_KT.xml' ...
'Mycobacterium_avium_subsp_avium_ATCC_25291.xml' ...
'Mycobacterium_fortuitum_subsp_fortuitum_DSM_46621.xml' ...
'Mycoplasma_hominis_ATCC_23114.xml' ...
'Mycoplasma_pneumoniae_309.xml' ...
'Neisseria_cinerea_ATCC_14685.xml' ...
'Neisseria_elongata_subsp_glycolytica_ATCC_29315.xml' ...
'Neisseria_flavescens_SK114.xml' ...
'Neisseria_macacae_ATCC_33926.xml' ...
'Neisseria_mucosa_ATCC_25996.xml' ...
'Neisseria_subflava_NJ9703.xml' ...
'Nevskia_ramosa_DSM_11499.xml' ...
'Oceanobacillus_picturae_strain_S1.xml' ...
'Ochrobactrum_anthropi_ATCC_49188.xml' ...
'Odoribacter_laneus_YIT_12061.xml' ...
'Odoribacter_splanchnicus_1651_6_DSM_20712.xml' ...
'Olsenella_profusa_F019501.xml' ...
'Olsenella_uli_DSM_7084.xml' ...
'Oribacterium_sinus_F0268.xml' ...
'Oxalobacter_formigenes_HOxBLS.xml' ...
'Oxalobacter_formigenes_OXCC13.xml' ...
'Paenibacillus_alvei_DSM_29.xml' ...
'Paenibacillus_barengoltzii_G22.xml' ...
'Paenibacillus_daejeonensis_DSM_15491.xml' ...
'Paenibacillus_graminis_C4D1M.xml' ...
'Paenibacillus_lactis_154.xml' ...
'Parabacteroides_distasonis_ATCC_8503.xml' ...
'Parabacteroides_goldsteinii_dnLKV18.xml' ...
'Parabacteroides_gordonii_DSM_23371.xml' ...
'Parabacteroides_johnsonii_DSM_18315.xml' ...
'Parabacteroides_merdae_ATCC_43184.xml' ...
'Parabacteroides_sp_D13.xml' ...
'Paracoccus_yeei_ATCC_BAA_599.xml' ...
'Paraprevotella_clara_YIT_11840.xml' ...
'Paraprevotella_xylaniphila_YIT_11841.xml' ...
'Parasutterella_excrementihominis_YIT_11859.xml' ...
'Parvimonas_micra_ATCC_33270.xml' ...
'Pediococcus_acidilactici_7_4.xml' ...
'Pediococcus_acidilactici_DSM_20284.xml' ...
'Pediococcus_pentosaceus_ATCC_25745.xml' ...
'Peptoniphilus_harei_ACS_146_V_Sch2b.xml' ...
'Peptoniphilus_indolicus_ATCC_29427.xml' ...
'Peptoniphilus_lacrimalis_DSM_7455.xml' ...
'Peptoniphilus_timonensis_JC401.xml' ...
'Peptostreptococcus_anaerobius_DSM_2949.xml' ...
'Peptostreptococcus_stomatis_DSM_17678.xml' ...
'Phascolarctobacterium_succinatutens_YIT_12067.xml' ...
'Plesiomonas_shigelloides_302_73.xml' ...
'Porphyromonas_asaccharolytica_DSM_20707.xml' ...
'Porphyromonas_endodontalis_ATCC_35406.xml' ...
'Porphyromonas_gingivalis_W83.xml' ...
'Porphyromonas_somerae_DSM_23386.xml' ...
'Porphyromonas_uenonis_60_3.xml' ...
'Porphyromonas_uenonis_DSM_23387.xml' ...
'Prevotella_albensis_DSM_11370.xml' ...
'Prevotella_bivia_DSM_20514.xml' ...
'Prevotella_brevis_ATCC_19188.xml' ...
'Prevotella_bryantii_B14.xml' ...
'Prevotella_bryantii_C21a.xml' ...
'Prevotella_buccae_ATCC_33574.xml' ...
'Prevotella_conceptionensis_9403948.xml' ...
'Prevotella_copri_CB7_DSM_18205.xml' ...
'Prevotella_corporis_DSM_18810.xml' ...
'Prevotella_denticola_DSM20614.xml' ...
'Prevotella_denticola_F0289.xml' ...
'Prevotella_disiens_FB035_09AN.xml' ...
'Prevotella_disiens_JCM_6334.xml' ...
'Prevotella_enoeca_JCM_12259.xml' ...
'Prevotella_intermedia_17.xml' ...
'Prevotella_intermedia_ATCC_25611.xml' ...
'Prevotella_loescheii_DSM_19665.xml' ...
'Prevotella_melaninogenica_ATCC_25845.xml' ...
'Prevotella_nanceiensis_DSM_19126.xml' ...
'Prevotella_nigrescens_ATCC_33563.xml' ...
'Prevotella_oralis_ATCC_33269.xml' ...
'Prevotella_pallens_ATCC_700821.xml' ...
'Prevotella_ruminicola_23.xml' ...
'Prevotella_salivae_DSM_15606.xml' ...
'Prevotella_shahii_JCM_12083.xml' ...
'Prevotella_stercorea_DSM_18206.xml' ...
'Prevotella_timonensis_4401737.xml' ...
'Prevotella_timonensis_CRIS_5C_B1.xml' ...
'Prevotella_veroralis_DSM_19559.xml' ...
'Propionibacterium_acidipropionici_ATCC_4875.xml' ...
'Propionibacterium_acnes_KPA171202.xml' ...
'Propionibacterium_avidum_44067.xml' ...
'Propionibacterium_freudenreichii_subsp_shermanii_CIRM_BIA1.xml' ...
'Propionibacterium_granulosum_DSM_20700.xml' ...
'Propionibacterium_jensenii_DSM_20535.xml' ...
'Propionibacterium_propionicum_F0230a.xml' ...
'Proteus_mirabilis_ATCC_35198.xml' ...
'Proteus_penneri_ATCC_35198.xml' ...
'Providencia_alcalifaciens_DSM_30120.xml' ...
'Providencia_rettgeri_DSM_1131.xml' ...
'Providencia_rustigianii_DSM_4541.xml' ...
'Providencia_stuartii_ATCC_25827.xml' ...
'Pseudobutyrivibrio_ruminis_AD2017.xml' ...
'Pseudoflavonifractor_capillosus_strain_ATCC_29799.xml' ...
'Pseudomonas_aeruginosa_NCGM2_S1.xml' ...
'Pseudomonas_alcaliphila_34.xml' ...
'Pseudomonas_monteilii_NBRC_103158.xml' ...
'Pseudomonas_nitroreducens_HBP1.xml' ...
'Pseudomonas_oleovorans_MOIL14HWK12.xml' ...
'Pseudoramibacter_alactolyticus_ATCC_23263.xml' ...
'Pyramidobacter_piscolens_W5455.xml' ...
'Ralstonia_sp_5_7_47FAA.xml' ...
'Raoultella_planticola_ATCC_33531.xml' ...
'Rhodococcus_equi_ATCC_33707.xml' ...
'Rhodococcus_equi_NBRC_101255.xml' ...
'Rhodococcus_rhodochrous_ATCC_21198.xml' ...
'Roseburia_hominis_A2_183.xml' ...
'Roseburia_intestinalis_L1_82.xml' ...
'Roseburia_inulinivorans_DSM_16841.xml' ...
'Roseomonas_mucosa_ATCC_BAA_692.xml' ...
'Rothia_aeria_F0474.xml' ...
'Rothia_dentocariosa_ATCC_17931.xml' ...
'Rothia_mucilaginosa_DY_18.xml' ...
'Ruminococcaceae_bacterium_D16.xml' ...
'Ruminococcus_albus_7.xml' ...
'Ruminococcus_bicirculans_80_3.xml' ...
'Ruminococcus_bromii_L2_63.xml' ...
'Ruminococcus_callidus_ATCC_2776001.xml' ...
'Ruminococcus_champanellensis_18P13.xml' ...
'Ruminococcus_flavefaciens_ATCC_19208.xml' ...
'Ruminococcus_flavefaciens_FD_1.xml' ...
'Ruminococcus_gauvreauii_DSM_19829.xml' ...
'Ruminococcus_gnavus_ATCC_29149.xml' ...
'Ruminococcus_lactaris_ATCC_29176.xml' ...
'Ruminococcus_obeum_A2_162.xml' ...
'Ruminococcus_sp_5_1_39BFAA.xml' ...
'Ruminococcus_sp_SR1_5.xml' ...
'Ruminococcus_torques_ATCC_27756.xml' ...
'Ruminococcus_torques_L2_14.xml' ...
'Salmonella_enterica_enterica_sv_Typhimurium_LT2.xml' ...
'Scardovia_inopinata_F0304.xml' ...
'Selenomonas_ruminantium_AC2024.xml' ...
'Serratia_fonticola_RB_25.xml' ...
'Serratia_liquefaciens_ATCC_27592.xml' ...
'Silanimonas_lenta_DSM_16282.xml' ...
'Slackia_exigua_ATCC_700122.xml' ...
'Slackia_piriformis_YIT_12062.xml' ...
'Solobacterium_moorei_DSM_22971.xml' ...
'Solobacterium_moorei_F0204.xml' ...
'Staphylococcus_arlettae_CVD059.xml' ...
'Staphylococcus_capitis_CR0101.xml' ...
'Staphylococcus_capitis_QN1.xml' ...
'Staphylococcus_caprae_C87.xml' ...
'Staphylococcus_cohnii_hu_01.xml' ...
'Staphylococcus_epidermidis_ATCC_12228.xml' ...
'Staphylococcus_equorum_subsp_equorum_Mu2.xml' ...
'Staphylococcus_haemolyticus_JCSC1435.xml' ...
'Staphylococcus_hominis_subsp_hominis_C80.xml' ...
'Staphylococcus_intermedius_ATCC_27335.xml' ...
'Staphylococcus_lugdunensis_HKU09_01.xml' ...
'Staphylococcus_pasteuri_SP1.xml' ...
'Staphylococcus_pettenkoferi_VCU012.xml' ...
'Staphylococcus_saprophyticus_subsp_saprophyticus_ATCC_15305.xml' ...
'Staphylococcus_sciuri_subsp_sciuri_Z8.xml' ...
'Staphylococcus_simulans_ACS_120_V_Sch1.xml' ...
'Staphylococcus_vitulinus_F1028.xml' ...
'Staphylococcus_warneri_SG1.xml' ...
'Staphylococcus_xylosus_DMB3_Bh1.xml' ...
'Staphylococcus_xylosus_NJ.xml' ...
'Stenotrophomonas_maltophilia_D457.xml' ...
'Stenotrophomonas_rhizophila_PCA13.xml' ...
'Stoquefichus_massiliensis_AP9.xml' ...
'Streptococcus_agalactiae_A909.xml' ...
'Streptococcus_anginosus_1_2_62CV.xml' ...
'Streptococcus_australis_ATCC_700641.xml' ...
'Streptococcus_constellatus_subsp_constellatus_SK53.xml' ...
'Streptococcus_constellatus_subsp_pharyngis_SK1060.xml' ...
'Streptococcus_cristatus_ATCC_51100.xml' ...
'Streptococcus_dysgalactiae_subsp_dysgalactiae_ATCC_27957.xml' ...
'Streptococcus_equinus_ATCC_9812.xml' ...
'Streptococcus_gallolyticus_subsp_gallolyticus_ATCC_43143.xml' ...
'Streptococcus_gordonii_str_Challis_substr_CH1.xml' ...
'Streptococcus_infantarius_subsp_infantarius_ATCC_BAA_102.xml' ...
'Streptococcus_infantis_ATCC_700779.xml' ...
'Streptococcus_intermedius_JTH08.xml' ...
'Streptococcus_lutetiensis_033.xml' ...
'Streptococcus_mitis_NCTC_12261.xml' ...
'Streptococcus_mutans_ATCC_25175.xml' ...
'Streptococcus_oralis_Uo5.xml' ...
'Streptococcus_parasanguinis_ATCC_903.xml' ...
'Streptococcus_parauberis_KCTC_11537.xml' ...
'Streptococcus_peroris_ATCC_700780.xml' ...
'Streptococcus_pleomorphus_DSM_20574.xml' ...
'Streptococcus_pseudopneumoniae_IS7493.xml' ...
'Streptococcus_salivarius_JIM8777.xml' ...
'Streptococcus_sanguinis_SK36.xml' ...
'Streptococcus_sp_2_1_36FAA.xml' ...
'Streptococcus_sp_I_G2.xml' ...
'Streptococcus_sp_I_P16.xml' ...
'Streptococcus_thermophilus_LMG_18311.xml' ...
'Streptococcus_thoraltensis_DSM_12221.xml' ...
'Streptococcus_uberis_0140J.xml' ...
'Streptococcus_vestibularis_F0396.xml' ...
'Subdoligranulum_variabile_DSM_15176.xml' ...
'Succinatimonas_hippei_YIT_12066.xml' ...
'Succinivibrio_dextrinosolvens_H5.xml' ...
'Sulfolobus_solfataricus_P2.xml' ...
'Sutterella_parvirubra_YIT_11816.xml' ...
'Sutterella_wadsworthensis_3_1_45B.xml' ...
'Tannerella_forsythia_ATCC_43037.xml' ...
'Tatumella_ptyseos_ATCC_33301.xml' ...
'Trabulsiella_guamensis_ATCC_49490.xml' ...
'Tropheryma_whipplei_str_Twist.xml' ...
'Trueperella_pyogenes_MS249.xml' ...
'Ureaplasma_parvum_serovar_1_str_ATCC_27813.xml' ...
'Ureaplasma_urealyticum_serovar_8_str_ATCC_27618.xml' ...
'Ureibacillus_thermosphaericus_str_Thermo_BF.xml' ...
'Varibaculum_cambriense_DSM_15806.xml' ...
'Veillonella_atypica_ACS_049_V_Sch6.xml' ...
'Veillonella_dispar_ATCC_17748.xml' ...
'Veillonella_parvula_Te3_DSM_2008.xml' ...
'Veillonella_ratti_ACS_216_V_Col6b.xml' ...
'Veillonella_sp_3_1_44.xml' ...
'Veillonella_sp_6_1_27.xml' ...
'Vibrio_fluvialis_560.xml' ...
'Vibrio_furnissii_NCTC_11218.xml' ...
'Vibrio_mimicus_MB_451.xml' ...
'Vibrio_parahaemolyticus_RIMD_2210633.xml' ...
'Weissella_cibaria_KACC_11862.xml' ...
'Weissella_confusa_LBAE_C39_2.xml' ...
'Weissella_paramesenteroides_ATCC_33313.xml' ...
'Yersinia_bercovieri_ATCC_43970.xml' ...
'Yersinia_enterocolitica_subsp_enterocolitica_8081.xml' ...
'Yersinia_frederiksenii_ATCC_33641.xml' ...
'Yersinia_kristensenii_ATCC_33638.xml' ...
'Yersinia_pseudotuberculosis_YPIII.xml' ...
'Yersinia_rohdei_ATCC_43380.xml' ...
'Yokenella_regensburgei_ATCC_43003.xml' ...
    };

extMetab = {};

for i = 1:length(speciesToConsider)
    disp(filenames(speciesToConsider(i)))
    models(i).COBRAmodel = readCbModel(strcat(directory, char(filenames(speciesToConsider(i)))));
    models(i).biomassReac = find(models(i).COBRAmodel.c);
    models(i).ngamReac = find(strncmp(models(i).COBRAmodel.rxns, 'NGAM', 4));
    if isempty(models(i).ngamReac)
        models(i).ngamReac = 0;
    end
    % exchange reactions
    IDs = find(strncmp(models(i).COBRAmodel.rxns, 'EX_', 3));
    ReactionIDName = models(i).COBRAmodel.rxns(IDs, :);
    Sense = 0*ones(length(IDs), 1);
    models(i).exchangeReactions = table(IDs, cellstr(ReactionIDName), Sense, 'VariableNames',{'ReacID' 'ReacName' 'SecretionSense'}, 'RowNames', strtrim(cellstr(num2str(IDs))'));

    % coupled reactions
    IDc = [];
    vmax = [];
    unlimited = max(models(i).COBRAmodel.ub);
    for k = 1:length(IDs)
        j = IDs(k);
        if ( 1 == 1 ) % only take restricted compounds into reactor and determine sense by set boundaries
            if models(i).COBRAmodel.lb(j) == -unlimited && models(i).COBRAmodel.ub(j) == unlimited
                continue
            end
            if models(i).COBRAmodel.lb(j) == -unlimited && models(i).COBRAmodel.ub(j) == 0
                continue
            end
            if models(i).COBRAmodel.lb(j) == 0 && models(i).COBRAmodel.ub(j) == unlimited
                continue
            end
            if models(i).COBRAmodel.lb(j) == models(i).COBRAmodel.ub(j)
                continue
            end
            if models(i).COBRAmodel.lb(j) == -unlimited || models(i).COBRAmodel.lb(j) == 0
                models(i).exchangeReactions.SecretionSense(num2str(j)) = -1;
                vmax(length(vmax)+1) = abs(models(i).COBRAmodel.ub(j));
            end
            if models(i).COBRAmodel.ub(j) == unlimited || models(i).COBRAmodel.ub(j) == 0
                models(i).exchangeReactions.SecretionSense(num2str(j)) = 1;
                vmax(length(vmax)+1) = abs(models(i).COBRAmodel.lb(j));
            end
            if models(i).exchangeReactions.SecretionSense(num2str(j)) ~= 0
                IDc(length(IDc)+1) = j;
                extMetab{length(extMetab)+1} = models(i).COBRAmodel.mets(find(models(i).COBRAmodel.S(:,j)));
            else
                error('Could not figure out SecretionSense!')
            end
        else % take all compounds into reactor, detect sense by position in reaction as educt or product
            models(i).exchangeReactions.SecretionSense(num2str(j)) = -1 * sign(models(i).COBRAmodel.S(find(models(i).COBRAmodel.S(:,j)),j));
            if models(i).exchangeReactions.SecretionSense(num2str(j)) == 1
                vmax(length(vmax)+1) = abs(models(i).COBRAmodel.lb(j));
            else
                vmax(length(vmax)+1) = abs(models(i).COBRAmodel.ub(j));
            end
            IDc(length(IDc)+1) = j;
            extMetab{length(extMetab)+1} = models(i).COBRAmodel.mets(find(models(i).COBRAmodel.S(:,j)));
        end
    end
    ReacNames = models(i).COBRAmodel.rxns(IDc, :);
    inhibitedCoupledReactions = 0 * ones(length(IDc), 1);
    ks = 0 * ones(length(IDc), 1);
    models(i).coupledReactions = table(IDc', cellstr(ReacNames), models(i).exchangeReactions.SecretionSense(strtrim(cellstr(num2str(IDc'))')), vmax', ks, inhibitedCoupledReactions,'VariableNames', {'ReacID' 'ReacName' 'SecretionSense' 'vmax' 'ks' 'inhibited'}, 'RowNames', strtrim(cellstr(num2str(IDc'))));
    models(i).FBAsolver = FBAsolver;
    models(i).modelName = strtok(filenames(speciesToConsider(i)),'.'); % get filename w/o trailing '.xml'
    
    returnModels(i) = convertToOnlyIrrevReac(models(i));
end

% save external compounds to file, sort & make unique for later loading

extMetab = [extMetab{:}]';
extMetab = unique(extMetab);

% prepare mapping to reactor compounds
for i = 1:length(speciesToConsider)
    ids = [];
    for j = 1:length(returnModels(i).coupledReactions.ReacID)
        % get compound of reaction
        compound = returnModels(i).COBRAmodel.mets(find(returnModels(i).COBRAmodel.S(:,returnModels(i).coupledReactions.ReacID(j))));
        % get index in reactor compounds
        ids(length(ids) + 1) = find(ismember(extMetab, compound));
    end
    
    returnModels(i).reactorCompoundIDs = ids;
end

end
